### ISSUE TITLE
dev49: seekページバグ対応

### ISSUE THREAD

**Issue by naotarian** [naotarian/developer-meets#105]
user_idが1以外のユーザーが立てたプロジェクトでアイコンが出ない
この画像のユーザーはid5で、アイコン画像設定済み(マイページには表示在り)

![図4](https://user-images.githubusercontent.com/59650885/141718582-6d185d8a-9207-4b2e-899d-a4242a51cefa.png)

**Comment by shimai0913** [comment]
@naotarian 
おれの方では見れるみたいだけど
再現できないパターンや
原因調べてないけど画像関連の部分不具合多い気がするな
ヘッダーの画像も別で勝手にAPI作ったもん

![スクリーンショット 2021-11-15 13 57 50](https://user-images.githubusercontent.com/58287922/141725121-5f612f86-39d2-47f1-958b-c6dfe8450866.png)

**Comment by shimai0913** [comment]
個人的にはstorage/の使い勝手が悪すぎると思ってるんだけど、
s3は最初から料金発生するんやっけ？置き換え無理？

**Comment by naotarian** [comment]
s3の料金体系次第かな
最初から金掛かるなら嫌や

**Comment by shimai0913** [comment]
id5がtwitterログインで作成したユーザーで、URLcodeが発行されてなかったとのこと
