### ISSUE TITLE
dev58: プロジェクト編集->プロジェクト画像設定してもDBにファイル名が入らない

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#125]
storage配下に画像ファイルは保存されるけど、DBにファイル名が保存されないかDetailで画像を取得できない

`projrcts`テーブルの`project_image`/`project_image_sp`にファイル名が入る認識なんだけど合ってる？

↑の認識が合ってるのであれば、DBにファイル名が入らないのは元からだっけ？

**Comment by naotarian** [comment]
認識はあってる。
project_imageに入らないのはバグですね
直します

**Comment by naotarian** [comment]
これ対応した
原因はProject.php(モデルファイル)のfillableに記載がなかったため

**Comment by naotarian** [comment]
あと、ProjectDetailPage.jsで、画像の呼び出ししてるところあると思うんだけど、そこの引数(projectのurl_code)が足りなくて表示できてなかったから直しておいた
jsの書き方辺だったら直しておいて
現状動くと思う
