### ISSUE TITLE
dev61: user_info/名前 遷移先の情報/機能について

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#131]
user1でログインしてる状態でuser2のページに遷移した時、プロジェクト掲載終了するとかいじれてるのは問題。

ルーティング見た感じ、my_pageと同じ機能のページ出してる状態だと思うから、見れる情報・触れる機能の制限は必要やと思う。

それとログインしてない状態で`/user_info/名前`遷移できないから、これは遷移できるようにしていいと思う。

**Comment by naotarian** [comment]
これやっぱり、user_infoとマイページ分けるわ
