### ISSUE TITLE
dev64: コメントテーブル追加

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#136]
yahooコメ参考

- プロジェクトごとにチャットルームを持つイメージ（ptoject_id）
- `@xxx`でメンションできるようにする
- `@`を入力した時点で出す候補としては、作成者+そのプロジェクトに一度でもコメントしてる人 
=> `/detail/{id}`アクセス時にそのプロジェクトIDのコメントを全取得する感じ
- メンション相手はフロント側で切り取る -> `target_user_id`カラムに入る
- コメントはメンションも含めてそのまま投げる -> @含めて全て`comment`カラムに入る

**Comment by naotarian** [comment]
しまいくん
新規コメントはエンドポイント/commentでmethodはpostで。
投げてほしいデータは下記
`{"user_id":1,"project_id":1,"target_user_id":"1,2,3","comment":"GET動詞が付くルートにアクセスするには、普通にブラウザからURLを入力すると、GETリクエストでのアクセスとなりますので、\n        GET動詞の付くルートが適応されます。フォームを使用しなければ、だいたいGETリクエストのアクセスなので想像しやすいと思います。\n        普通にaタグのリンクで遷移するのもGETリクエストです。"}`
