### ISSUE TITLE
dev74: コメント投稿、編集、削除時に通知が欲しい

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#158]
とりあえずスピナーとアラート的なのが欲しいけど、アプリ全体でデザインの統一性が必要な気がする
material ui だとこんな感じ↓
[material ui Alert](https://mui.com/components/alert/)
[material ui progress](https://mui.com/components/progress/#main-content)
[実装例](https://coders-shelf.com/react-spinner-and-message/)

**Comment by naotarian** [comment]
これいいね、実装してくれ。
これをやるにあたって、バックエンドで何かすることある？？
