### ISSUE TITLE
dev14: scriptタグを毎回書くのか問題

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#21]
reactコンポーネント作って、blade.phpに入れるとき
`<script src="{{ mix('/js/Example.js') }}"></script>`
これを毎回書くのが面倒

最上位の親blade的なのに書いておいて、それ以下のbladeでは書かなくてOK的な感じにできればベスト

**Comment by shimai0913** [comment]
<script src="{{ mix('/js/Example.js') }}"></script>
この入れ方したら、コンポーネント作るたびに書く必要があるのは変わってないから、
アスタみたいなワイルドカードで全読み込みをしてほしい
やり方は調べてないから分からん

**Comment by naotarian** [comment]
<script src="{{ mix('/js/*') }}"></script>こういうこと？
そもそもできるかわからん。調査して実装できそうならするんやで
