### ISSUE TITLE
dev22: 全プロジェクト情報を返すAPIの作成

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#45]
CardListPage.jsから全プロジェクトの情報を取りたい
フロント側は仮で作っててるけど、APIのエンドポイントと返すjsonデータの構成を共有する

**Comment by naotarian** [comment]
これなんやけど、今のdevelopをpullしてくれ。
ProjectListPage.jsでGETリクエスト投げた先の処理を追記してある(戻り値はProjectListPage.jsでconsole.logで確認してあるが、しまいが仮で作ってたSampleProjectのデータと同じ形式だと思う)

現状、レンダリングする時にSampleをデータとしてレンダリングしてると思うけど、それを戻り値に変更する方法がわからんかったからとりあえずAPIだけ作成してある。
developをpullして作業してくれ。
