### ISSUE TITLE
dev25: 詳細ページに参加申請機能置き換え

### ISSUE THREAD

**Issue by shimai0913** [naotarian/developer-meets#50]
dev17 の後

叩くべきAPIのエンドポイント → [POST] "~/api/application" + データは{project_info}全部 
POSTだと思うから、なんのデータを一緒に投げればいいか

react側で現状この形で持ってる -> object型？
```
{
"project_data": "xxx",
"project_name": "xxx",
}
```
```
$ projectinfo = postされたdata;
projectinfo[project_data];
```

PHP側ではobject型エラー？ -> 連想配列の形でもらえたら多分可能

**Comment by shimai0913** [comment]
@naonao0702 
`dev25`でブランチきってる
`~/api/application`にPOSTしてる
参加申請ボタン押した時色々console.log出してるからわかると思うけど、
今はobject型のデータ渡してPOSTしてる状況

**Comment by naotarian** [comment]
API処理作ったで。
受け取りはうまくいってた。
とりあえず、ここでやることって、DBの値更新(申請の発行)だけだから、完了したのか、すでに申請済みなのかとかっていうステだけリターンしておいたで

申請完了したら、画面はどうする？
問答無用でマイページの申請中一覧のところに飛ばすか、「申請中のプロジェクトはこちらから確認できます」みたいなリンクだけ表示して、飛ぶか飛ばないかはユーザー次第みたいなのにするか。

どちらにせよ、申請中プロジェクトがどこから確認できるかは示した方がいいよな

**Comment by shimai0913** [comment]
申請できてるか見た目で見れるようにするのは要るよな。

個人的にページ遷移はしてあげなくて良い派なんだけど、
その場合申請処理問題なく走りましたよーの通知を出すか、「申請する」のボタンを「申請済み」とかに変えてあげるかなとは思ってる。

ページ遷移するならマイページに飛ばすのが正解な気がするけど、その場合はlaravel側の処理よな？
好きに決めて良いでリーダー！！

**Comment by naotarian** [comment]
画面繊維の話やが、無しで。
つまり、ボタンを申請済みに変えるのと、申請したら、申請したよっていうメッセージ出すが正解だと思うわ
