### ISSUE TITLE
dev40: /seekでプロジェクトが奇数個だったら左寄せにしたい

### ISSUE THREAD

**Issue by naotarian** [naotarian/developer-meets#92]
![図2](https://user-images.githubusercontent.com/59650885/141393866-3dc142a4-99e8-4f7b-84a2-c5f87f565953.png)

中央の方がいいと判断したならそのままでいい
個人的に左寄せの方がきれいなんじゃないかと思った

**Comment by shimai0913** [comment]
これは考えを言うと、
横1列に4つまでカードが表示されるようmax-widthで制御してる。

でここからは未実装だけど、1ページに12個までしか表示しないようにしようと思ってて、2ページ目3ページ目の展開をしようと思ってる。
12個にすることで、画面サイズが何であっても、横1列のカードの数は 4or 3 or 2 or 1 になるからflex centerのままで表示がおかしくなることはないはず。

最終ページのカード数が5以上12以下の時にこれ発生するわけやけど、いっぱいプロジェクトあったら問題ないというユーザー任せの実装や。

**Comment by naotarian** [comment]
意図的なら何の問題もないのでclose
