### ISSUE TITLE
dev46: 絞り込みバグ発見

### ISSUE THREAD

**Issue by naotarian** [naotarian/developer-meets#98]
複数の項目で絞り込んだ場合、重複したデータが出現するバグ
![図3](https://user-images.githubusercontent.com/59650885/141395739-52755478-3a30-4c0d-94ec-68dd788f3ce4.png)

同じデータが複数の絞り込みパターンに該当する場合、全て出てしまうのが原因??
とりあえず調査頼みますー

**Comment by shimai0913** [comment]
このバグがわからん
どうやれば再現できるかな？
